version: "3.9"

services:
  app:
    image: yodaskillme/aspnetapp
    ports:
      - 8000:80
    links:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  database:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"