version: "3.9"

services:
  app:
    image: yodaskillme/aspnetapp
    ports:
      - 44323:80
    links:
      - database

  database:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"